### ISSUE TITLE
有没有这方面的参考资料?

### ISSUE THREAD

**Issue by yanweijia** [picone/MemoryPageManage#1]
有没有这方面的参考资料?

**Comment by picone** [comment]
这个是我的课程设计作业，太赶所以没用写太多的介绍。
具体可以参考《计算机操作系统》这本书。

**Comment by yanweijia** [comment]
不用了,谢谢,我已经参考其他资料写了一份,乘法模拟手算法,出发用的使商法 https://github.com/yanweijia/BigInteger
